---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bootstrap
data:
  authorize.conf: |
    [tokens_auth]
    disabled = true
  indexes.conf: |+
    [test]
    coldPath = $SPLUNK_DB/test/colddb
    enableDataIntegrityControl = 0
    enableTsidxReduction = 0
    homePath = $SPLUNK_DB/test/db
    maxTotalDataSizeMB = 512000
    thawedPath = $SPLUNK_DB/test/thaweddb

    [kubernetes]
    coldPath = $SPLUNK_DB/kubernetes/colddb
    enableDataIntegrityControl = 0
    enableTsidxReduction = 0
    homePath = $SPLUNK_DB/kubernetes/db
    maxTotalDataSizeMB = 512000
    thawedPath = $SPLUNK_DB/kubernetes/thaweddb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk
  labels:
    app: splunk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
      - name: splunk
        image: splunk/splunk:8.1.3
        env:
        - name: SPLUNK_START_ARGS
          value: --accept-license
        - name: SPLUNK_PASSWORD
          value: password
        - name: SPLUNK_HEC_TOKEN
          value: k8stoken
        - name: SPLUNK_DISABLE_POPUPS
          value: "true"
        volumeMounts:
        - name: bootstrap
          mountPath: "/opt/splunk-etc/system/local"
          readOnly: true
      volumes:
      - name: bootstrap
        configMap:
          name: bootstrap
          items:
          - key: "authorize.conf"
            path: "authorize.conf"
          - key: "indexes.conf"
            path: "indexes.conf"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: splunk
  name: splunk
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: splunk
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: splunk-hec
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: splunk
  ports:
  - protocol: TCP
    port: 8088
    targetPort: 8088
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: splunk
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: splunk
            port:
              number: 80
